eyetracker.hw.gazepoint.gp3.EyeTracker:
    name: tracker
    enable: IOHUB_BOOL
    model_name:
        IOHUB_LIST:
            valid_values: [GP3, GP3 HD]
            min_length: 1
            max_length: 1
    serial_number:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    network_settings:
        ip_address: IOHUB_IP_ADDRESS_V4
        port:
            IOHUB_INT:
                min: 1
                max: 9999
    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 2048
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.020
    monitor_event_types:           
        IOHUB_LIST:
            valid_values: [BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent]
            min_length: 1
            max_length: 3
    runtime_settings:
        sampling_rate: Auto
        track_eyes: [BINOCULAR,]
    calibration:
        use_builtin: IOHUB_BOOL
        target_duration:
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
        target_delay: 
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
    device_number: 0
    manufacturer_name: GazePoint
    builder_hides: ['builder_hides', 'enable', 'device_number', 'device_timer', 'auto_report_events', 'runtime_settings.track_eyes', 'calibration.use_builtin']
