Display:
    enable: IOHUB_BOOL
    name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True
    device_number:
        IOHUB_INT:
            min: 0
            max: 7
    reporting_unit_type: [ org, pix, pixel, pixels, deg, degree, degrees, cm, mm, inch, norm, normalize, normalized, percent, percentage] 
    origin: [ center , top_left , bottom_left]
    physical_dimensions:
        width:
            IOHUB_FLOAT:
                min: 1.0
                max: 2048.0
                required: True
        height:
            IOHUB_FLOAT:
                min: 1.0
                max: 2048.0
                required: True
        unit_type: [ mm, cm, inch ]
    default_eye_distance:
        surface_center:
            IOHUB_FLOAT:
                min: 1.0
                max: 2048.0
                required: True
        unit_type: [ mm, cm, inch ]
    psychopy_monitor_name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            required: True
    override_using_psycho_settings: IOHUB_BOOL
    save_events: False
    stream_events: False
    auto_report_events: False    
    event_buffer_length: 0    
    monitor_event_types:
    model_name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
    manufacturer_name:
        IOHUB_STRING:
            min_length: 1
            max_length: 64    
            default: N/A
