data_store:
  enable: true
monitor_devices:
- Display:
    color_space: rgb
    default_eye_distance:
      surface_center: 500
      unit_type: mm
    device_number: 0
    name: display
    physical_dimensions:
      height: 340
      unit_type: mm
      width: 590
    psychopy_monitor_name: default
    reporting_unit_type: pix
- Keyboard:
    name: keyboard
- Mouse:
    name: mouse
- Experiment:
    name: experimentRuntime
- eyetracker.hw.sr_research.eyelink.EyeTracker:
    calibration:
      auto_pace: true
      pacing_speed: 1.5
      screen_background_color:
      - 0.0
      - 1.0
      - 0.0
      target_attributes:
        inner_color:
        - -1.0
        - 1.0
        - -1.0
        inner_diameter: 6
        outer_color:
        - 1.0
        - -1.0
        - 1.0
        outer_diameter: 33
      target_type: CIRCLE_TARGET
      type: NINE_POINTS
    default_native_data_file_name: et_data
    device_timer:
      interval: 0.001
    enable: true
    enable_interface_without_connection: false
    event_buffer_length: 1024
    model_name: EYELINK 1000 DESKTOP
    monitor_event_types:
    - MonocularEyeSampleEvent
    - BinocularEyeSampleEvent
    - FixationStartEvent
    - FixationEndEvent
    - SaccadeStartEvent
    - SaccadeEndEvent
    - BlinkStartEvent
    - BlinkEndEvent
    name: tracker
    network_settings: 100.1.1.1
    runtime_settings:
      sample_filtering:
        FILTER_FILE: FILTER_LEVEL_2
        FILTER_ONLINE: FILTER_OFF
      sampling_rate: 500
      track_eyes: RIGHT_EYE
      vog_settings:
        pupil_center_algorithm: CENTROID_FIT
        pupil_measure_types: PUPIL_AREA
        tracking_mode: PUPIL_CR_TRACKING
    save_events: true
    simulation_mode: false
    stream_events: true
