data_store:
  enable: true
monitor_devices:
- Display:
    default_eye_distance:
      surface_center: 500
      unit_type: mm
    device_number: 0
    name: display
    physical_dimensions:
      height: 340
      unit_type: mm
      width: 590
    psychopy_monitor_name: default
    reporting_unit_type: pix
- Keyboard:
    name: keyboard
- Mouse:
    name: mouse
- Experiment:
    name: experimentRuntime
- eyetracker.hw.mouse.EyeTracker:
    controls:
      blink:
      - LEFT_BUTTON
      - RIGHT_BUTTON
      move: RIGHT_BUTTON
      saccade_threshold: 0.5
    enable: true
    monitor_event_types:
    - MonocularEyeSampleEvent
    - FixationStartEvent
    - FixationEndEvent
    - SaccadeStartEvent
    - SaccadeEndEvent
    - BlinkStartEvent
    - BlinkEndEvent
    name: tracker
    runtime_settings:
      sampling_rate: 50
