name: PsychoPy flake

on: [push]

jobs:

  testflake:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2
