name: pytest

on: [push]

permissions:
  contents: read

jobs:

  push_sub_projects:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Pre-Install
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Remove unecessary dependencies for psychopy-lib
      run: |
        pdm remove wxpython
        pdm remove pyqt5
