name: PsychoPy pytesting

on: [push]

jobs:

  testsuite:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Pre-Install
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install wheel
        pip install six  # just needed for configobj
        pip install distro  # used by createInitFile
        python ./building/plat_custom_installs.py

    - name: Install Depends
      run: |
        # to install all dependencies
        pip install .
        # remove psychopy itself so that this
        pip uninstall psychopy

    - name: Test with pytest
      run: |
        pytest psychopy/tests -v
#
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        fail_ci_if_error: true
